### ISSUE TITLE
site don't modified

### ISSUE THREAD

**Issue by adabadadudu** [man-va-code/man-va-code.ir#1]
please uploaf file to http://man-va-code.ir/ site

**Comment by mehdisayyadnahed** [comment]
.راه انداختم mahyadnameh.ir سایت رو روی دامنه‌ی

**Comment by adabadadudu** [comment]
مبارک باشد.
از سربازی چه خبر ؟؟

**Comment by mehdisayyadnahed** [comment]
.آدم رو از کار و زندگی میندازه
(: ولی این نیز بگذرد
